
import { ClinicEvent } from './types';

// REPLACE THIS with your actual deployed Google Apps Script URL for production
export const GOOGLE_APPS_SCRIPT_URL = "https://script.google.com/macros/s/AKfycbz_your_actual_deployment_id/exec";

export const EVENTS: ClinicEvent[] = [
    {
        id: 'dec-17-2025',
        title: 'Unstoppable Community Event',
        date: '2025-12-17',
        dateDisplay: 'December 17, 2025',
        time: '5:00 PM - 7:00 PM',
        location: 'Inglewood',
        city: 'Inglewood',
        address: '123 W. Manchester Blvd, Inglewood, <CA> 90301',
        program: 'Community Wellness',
        lat: 33.9719,
        lng: -118.2108,
        description: 'Join us for an evening of connection, resources, and community support.'
    },
    {
        id: 'dec-19-2025',
        title: 'Community Health & Wellness Event',
        date: '2025-12-19',
        dateDisplay: 'Friday, December 19, 2025',
        time: '12:00 PM - 4:00 PM',
        location: 'Compton',
        city: 'Compton',
        address: 'Gym Basketball Courts, 11251 Compton Ave, Compton, CA 90059',
        program: 'Community Fair',
        lat: 33.8962,
        lng: -118.2207,
        description: 'Free health screenings, wellness resources, and community support.',
        saveTheDate: true
    },
    {
        id: 'jan-09-2026',
        title: 'Unstoppable Workshop: Social Connections',
        date: '2026-01-09',
        dateDisplay: 'Friday, January 9, 2026',
        time: '10:15 AM - 11:45 AM',
        location: 'Palmdale',
        city: 'Palmdale',
        address: '2072 E. Palmdale Blvd, Palmdale, CA 93550',
        program: 'Unstoppable Workshop',
        lat: 34.5801,
        lng: -118.1164,
        description: 'Build authentic connections and community in a safe, welcoming space.'
    },
    {
        id: 'jan-10-2026',
        title: 'Community Walk & Run',
        date: '2026-01-10',
        dateDisplay: 'Saturday, January 10, 2026',
        time: '8:00 AM',
        location: 'Inglewood',
        city: 'Inglewood',
        address: '123 W. Manchester Blvd, Inglewood, CA 90301',
        program: 'Community Walk & Run',
        lat: 33.9719,
        lng: -118.2108,
        description: 'Join our monthly community walk and run. Community building through movement.'
    },
    {
        id: 'jan-21-2026',
        title: 'Unstoppable Wellness Meetup',
        date: '2026-01-21',
        dateDisplay: 'Wednesday, January 21, 2026',
        time: '6:00 PM - 7:15 PM',
        location: 'Inglewood',
        city: 'Inglewood',
        address: '123 W. Manchester Blvd, Inglewood, CA 90301',
        program: 'Unstoppable Wellness Meetup',
        lat: 33.9719,
        lng: -118.2108,
        description: 'Safe space for authentic healing conversations. Set-up at 5:30 PM.'
    },
    {
        id: 'feb-06-2026',
        title: 'Unstoppable Workshop: Community Advocacy & Empowerment',
        date: '2026-02-06',
        dateDisplay: 'Friday, February 6, 2026',
        time: '10:15 AM - 11:45 AM',
        location: 'Palmdale',
        city: 'Palmdale',
        address: '2072 E. Palmdale Blvd, Palmdale, CA 93550',
        program: 'Unstoppable Workshop',
        lat: 34.5801,
        lng: -118.1164,
        description: 'Learn about advocacy and empower yourself and your community.'
    },
    {
        id: 'feb-14-2026',
        title: 'Community Walk & Run',
        date: '2026-02-14',
        dateDisplay: 'Saturday, February 14, 2026',
        time: '8:00 AM',
        location: 'Inglewood',
        city: 'Inglewood',
        address: '123 W. Manchester Blvd, Inglewood, CA 90301',
        program: 'Community Walk & Run',
        lat: 33.9719,
        lng: -118.2108,
        description: 'Join our monthly community walk and run.'
    },
    {
        id: 'feb-18-2026',
        title: 'Unstoppable Wellness Meetup',
        date: '2026-02-18',
        dateDisplay: 'Wednesday, February 18, 2026',
        time: '6:00 PM - 7:15 PM',
        location: 'Inglewood',
        city: 'Inglewood',
        address: '123 W. Manchester Blvd, Inglewood, CA 90301',
        program: 'Unstoppable Wellness Meetup',
        lat: 33.9719,
        lng: -118.2108,
        description: 'Safe space for authentic healing conversations.'
    },
    {
        id: 'mar-06-2026',
        title: 'Unstoppable Workshop: Mental Health Awareness',
        date: '2026-03-06',
        dateDisplay: 'Friday, March 6, 2026',
        time: '10:15 AM - 11:45 AM',
        location: 'Palmdale',
        city: 'Palmdale',
        address: '2072 E. Palmdale Blvd, Palmdale, CA 93550',
        program: 'Unstoppable Workshop',
        lat: 34.5801,
        lng: -118.1164,
        description: 'Explore mental health awareness and destigmatize mental wellness.'
    },
    {
        id: 'mar-14-2026',
        title: 'Community Walk & Run',
        date: '2026-03-14',
        dateDisplay: 'Saturday, March 14, 2026',
        time: '8:00 AM',
        location: 'Inglewood',
        city: 'Inglewood',
        address: '123 W. Manchester Blvd, Inglewood, CA 90301',
        program: 'Community Walk & Run',
        lat: 33.9719,
        lng: -118.2108,
        description: 'Join our monthly community walk and run.'
    },
    {
        id: 'mar-18-2026',
        title: 'Unstoppable Wellness Meetup',
        date: '2026-03-18',
        dateDisplay: 'Wednesday, March 18, 2026',
        time: '6:00 PM - 7:15 PM',
        location: 'Inglewood',
        city: 'Inglewood',
        address: '123 W. Manchester Blvd, Inglewood, CA 90301',
        program: 'Unstoppable Wellness Meetup',
        lat: 33.9719,
        lng: -118.2108,
        description: 'Safe space for authentic healing conversations.'
    },
    {
        id: 'mar-27-2026',
        title: 'Unstoppable Workshop: Access to Healthcare',
        date: '2026-03-27',
        dateDisplay: 'Friday, March 27, 2026',
        time: '10:15 AM - 11:45 AM',
        location: 'Palmdale',
        city: 'Palmdale',
        address: '2072 E. Palmdale Blvd, Palmdale, CA 93550',
        program: 'Unstoppable Workshop',
        lat: 34.5801,
        lng: -118.1164,
        description: 'Navigate healthcare access and resources in your community.'
    },
    {
        id: 'mar-28-2026',
        title: '5K Walk + Health Fair',
        date: '2026-03-28',
        dateDisplay: 'Saturday, March 28, 2026',
        time: 'TBD',
        location: 'East Los Angeles',
        city: 'East Los Angeles',
        address: 'East Los Angeles, CA',
        program: 'Community Fair',
        lat: 34.0233,
        lng: -118.2013,
        description: 'Community health event with 5K walk and health screenings.',
        saveTheDate: true
    },
    {
        id: 'may-08-2026',
        title: 'Unstoppable Workshop: Cultural Competence & Inclusion',
        date: '2026-05-08',
        dateDisplay: 'Friday, May 8, 2026',
        time: '10:15 AM - 11:45 AM',
        location: 'Palmdale',
        city: 'Palmdale',
        address: '2072 E. Palmdale Blvd, Palmdale, CA 93550',
        program: 'Unstoppable Workshop',
        lat: 34.5801,
        lng: -118.1164,
        description: 'Celebrate cultural diversity and build inclusive communities.'
    },
    {
        id: 'jun-05-2026',
        title: 'Unstoppable Workshop: Physical Well-being',
        date: '2026-06-05',
        dateDisplay: 'Friday, June 5, 2026',
        time: '10:15 AM - 11:45 AM',
        location: 'Palmdale',
        city: 'Palmdale',
        address: '2072 E. Palmdale Blvd, Palmdale, CA 93550',
        program: 'Unstoppable Workshop',
        lat: 34.5801,
        lng: -118.1164,
        description: 'Explore physical health, movement, and wellness practices.'
    },
    {
        id: 'jun-06-2026',
        title: 'Health + Resources Fair',
        date: '2026-06-06',
        dateDisplay: 'Saturday, June 6, 2026',
        time: 'TBD',
        location: 'Lynwood',
        city: 'Lynwood',
        address: 'Lynwood, CA',
        program: 'Community Fair',
        lat: 33.9229,
        lng: -118.2114,
        description: 'Community health and resources fair.',
        saveTheDate: true
    },
    {
        id: 'jul-10-2026',
        title: 'Unstoppable Workshop: Financial Wellness',
        date: '2026-07-10',
        dateDisplay: 'Friday, July 10, 2026',
        time: '10:15 AM - 11:45 AM',
        location: 'Palmdale',
        city: 'Palmdale',
        address: '2072 E. Palmdale Blvd, Palmdale, CA 93550',
        program: 'Unstoppable Workshop',
        lat: 34.5801,
        lng: -118.1164,
        description: 'Build financial literacy and economic empowerment.'
    },
    {
        id: 'aug-07-2026',
        title: 'Unstoppable Workshop: Environmental Health',
        date: '2026-08-07',
        dateDisplay: 'Friday, August 7, 2026',
        time: '10:15 AM - 11:45 AM',
        location: 'Palmdale',
        city: 'Palmdale',
        address: '2072 E. Palmdale Blvd, Palmdale, CA 93550',
        program: 'Unstoppable Workshop',
        lat: 34.5801,
        lng: -118.1164,
        description: 'Understand environmental health and community sustainability.'
    },
    {
        id: 'aug-08-2026',
        title: 'Back to School Wellness Event',
        date: '2026-08-08',
        dateDisplay: 'Saturday, August 8, 2026',
        time: 'TBD',
        location: 'Huntington Park',
        city: 'Huntington Park',
        address: 'Huntington Park, CA',
        program: 'Community Fair',
        lat: 33.9773,
        lng: -118.2272,
        description: 'Back to school health and wellness fair.',
        saveTheDate: true
    },
    {
        id: 'dec-12-2026',
        title: 'Toy Distribution',
        date: '2026-12-12',
        dateDisplay: 'Saturday, December 12, 2026',
        time: 'TBD',
        location: 'Huntington Park',
        city: 'Huntington Park',
        address: 'Huntington Park, CA',
        program: 'Community Fair',
        lat: 33.9773,
        lng: -118.2272,
        description: 'Holiday toy distribution event.',
        saveTheDate: true
    }
];

export const I18N = {
    en: {
        app_title: 'Clinic Events',
        app_subtitle: 'Free health resources & community events near you',
        qc_title: 'Quick Check-In',
        rsvp_title: 'Save Your Spot',
        qc_intro: 'Welcome! This quick check-in helps our team support you today.',
        rsvp_intro: 'Let us know you\'re coming! We\'ll save a spot for you and send a reminder.',
        q_needs_label: 'How can we help support you today?',
        needs_screening: 'Health screening (blood pressure, glucose, HIV, etc.)',
        needs_resources: 'Help with resources (housing, food, insurance, mental health support)',
        needs_both: 'I need both screenings and resources',
        needs_goodies: 'I’m here for the event and community gifts',
        needs_checkin: 'I would like someone to check in on me',
        q_contact_label: 'BEST WAY TO REACH YOU (CHOOSE ONE)',
        contact_text: 'TEXT',
        contact_email: 'EMAIL',
        contact_none: 'NO FOLLOW-UP NEEDED',
        q_name_label: 'Full Name',
        q_phone_label: 'Phone Number',
        q_email_label: 'Email Address',
        sms_consent: 'Yes, you can text me about today’s visit and Health Matters Clinic updates. Message and data rates may apply. Reply STOP to opt out.',
        qc_disclaimer: 'This check-in is for support and coordination only. It is not medical advice. If you have an urgent medical emergency, please call 911.',
        submit_btn: 'Confirm RSVP',
        toast_copied: 'Link copied to clipboard.',
        donate_now: 'Donate Now',
        explore_programs: 'Explore Programs',
        showing_events: (count: number) => `Showing ${count} event${count !== 1 ? 's' : ''}`,
        no_events: 'No events found for this filter.',
        upcoming: 'Upcoming Events',
        past: 'Past Events',
        success_rsvp: 'You’re all set! Check your email for confirmation.',
        error_rsvp: 'Could not submit. Please try again.',
        clear_filters: 'Clear Filters',
        copyright: 'Health Matters Clinic. All rights reserved.',
        add_to_calendar: 'ADD TO CALENDAR',
        google_cal: 'GOOGLE',
        outlook_cal: 'OUTLOOK',
        apple_cal: 'APPLE'
    },
    es: {
        app_title: 'Eventos de la clínica',
        app_subtitle: 'Recursos de salud gratis y eventos comunitarios cerca de usted',
        qc_title: 'Registro rápido',
        rsvp_title: 'Reserva tu lugar',
        qc_intro: '¡Bienvenido! Este registro rápido ayuda a nuestro equipo a apoyarle hoy.',
        rsvp_intro: '¡Haznos saber que vendrás! Guardaremos un lugar para ti y te enviaremos un recordatorio.',
        q_needs_label: '¿Cómo podemos apoyarle hoy?',
        needs_screening: 'Evaluación de salud (presión arterial, glucosa, VIH, etc.)',
        needs_resources: 'Ayuda con recursos (vivienda, comida, seguro, apoyo mental)',
        needs_both: 'Necesito ambos (evaluación y recursos)',
        needs_goodies: 'Solo vengo por el evento y los regalos',
        needs_checkin: 'Me gustaría que alguien se comunique conmigo',
        q_contact_label: 'MEJOR FORMA DE CONTACTARLE (ELIJA UNA)',
        contact_text: 'TEXTO',
        contact_email: 'EMAIL',
        contact_none: 'NO NECESITO SEGUIMIENTO',
        q_name_label: 'Nombre completo',
        q_phone_label: 'Número de teléfono',
        q_email_label: 'Correo electrónico',
        sms_consent: 'Sí, pueden enviarme mensajes de texto sobre la visita de hoy. Pueden aplicarse tarifas de mensajes y datos. Responda STOP para dejar de recibir mensajes.',
        qc_disclaimer: 'Este registro es solo para apoyo. No es consejo médico. Si tiene una emergencia médica urgente, llame al 911.',
        submit_btn: 'Confirmar RSVP',
        toast_copied: 'Enlace copiado.',
        donate_now: 'Donar Ahora',
        explore_programs: 'Explorar Programas',
        showing_events: (count: number) => `Mostrando ${count} evento${count !== 1 ? 's' : ''}`,
        no_events: 'No se encontraron eventos.',
        upcoming: 'Próximos Eventos',
        past: 'Eventos Pasados',
        success_rsvp: '¡Listo! Revisa tu correo para la confirmación.',
        error_rsvp: 'No se pudo enviar. Intente de nuevo.',
        clear_filters: 'Borrar Filtros',
        copyright: 'Health Matters Clinic. Todos los derechos reservados.',
        add_to_calendar: 'AGREGAR AL CALENDARIO',
        google_cal: 'GOOGLE',
        outlook_cal: 'OUTLOOK',
        apple_cal: 'APPLE'
    }
};
